name = "bin2-pull"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
REGISTRY_SERVICE = "bin2.nthesis.ai"
REGISTRY_TOKEN_REALM = "https://bin2.nthesis.ai/v2/token"
REGISTRY_JWKS_URL = "https://bin2.nthesis.ai/.well-known/jwks.json"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "bin2"
remote = true
